### ISSUE TITLE
Gstreamer Block for Cinder 0.9.1

### ISSUE THREAD

**Issue by pawansjadhav** [brucelane/Cinder-GStreamer#1]
Hi,

We are deliberately looking for the Cinder 0.9.0/0.9.1 integration with the Gstreamer. We are facing several issues and are not able to integrate the block with the Cinder Framework. 

Please help us and create/update the required block/code.

Thanks & Regards,
Pawan

**Comment by brucelane** [comment]
hi,
I will give it a try!
Have you managed to test it already?

**Comment by pawansjadhav** [comment]
Hi,

Yes I have tried to compile with cinder Cinder 0.9.0/0.9.1 version, however found several issues.

Thanks & Regards,
Pawan

**Comment by brucelane** [comment]
Have you tryed this fork: https://github.com/ellion/_2RealGStreamerWrapper ?
What Operating System are you on?
There is also some work in the main Cinder repository about gStreamer

**Comment by Immature29** [comment]
Hi,

I have tried using your wrapper class. It is getting compiled but when added to another project created with Tinderbox it shows errors with input file paths. I have checked adding all the necessary paths but still it shows errors.

**Comment by pawansjadhav** [comment]
We are using Windows 7 as operating system
we have compiled multiple Gstreamer blocks however we are getting same error in all the libraries including block Cinder-GStreamer errors are same when we try to complile the block with Cinder 0.9.0/0.9.1

Error:
Error	26	error C2061: syntax error : identifier 'RendererGl'	c:\users\Pawanj\documents\_2realgstreamerwrapper-master\samples\cindergstreamergui\src\cindergstreamerapp.cpp	401	1	CinderGStreamerTest
Error	7	error C2057: expected constant expression	c:\program files (x86)\microsoft visual studio 12.0\vc\include\ratio	44	1	CinderGStreamerTest
Error	8	error C2039: 'value' : is not a member of 'std::_Safe_multX<0x01,0x0989680,false>'	c:\program files (x86)\microsoft visual studio 12.0\vc\include\ratio	44	1	CinderGStreamerTest
Error	5	error C2039: 'value' : is not a member of 'std::_Safe_multX<0x01,0x01,false>'	c:\program files (x86)\microsoft visual studio 12.0\vc\include\ratio	44	1	CinderGStreamerTest
